### ISSUE TITLE
Passing dynamic data

### ISSUE THREAD

**Issue by caleb654** [monterail/intelligence#3]
For example "Siri, add 5 reps." Instead of creating representable entities, I want to be able to pass dynamic data like numbers or strings. Is that possible?

**Comment by wrbl606** [comment]
While it is a bit more advanced usage of the plugin, the scenario is supported, as the target variable doesn't have to be feed from an app-delivered entity.

For more advanced examples of the `intelligence` usage, see [this article](https://www.monterail.com/blog/flutter-development-services-OS-integration): the HR Tech demo touches on the subject of delivering integers via Siri-driven workflows.

**Comment by caleb654** [comment]
Thanks! I got this code working. The only problem is it doesn't take the reps from the initial phrase. It asks again "what number?" and then finally gets it after I say just the number. I saw the disambiguation dialog in the example project, but that's not really what I want. I just want it to pull the number directly from the initial query. Am I missing something obvious?

```
struct AddRepsIntent: AppIntent {
    static var title: LocalizedStringResource = "Add Reps"

    @Parameter(title: "Reps", description: "The number or reps to add")
    var reps: Int

    func perform() async throws -> some IntentResult {

        IntelligencePlugin.notifier.push(String(reps))
        return .result()
    }
}

struct AppShortcuts: AppShortcutsProvider {
    static var appShortcuts: [AppShortcut] {
        AppShortcut(
            intent: AddRepsIntent(),
            phrases: [
                "Add \(\.$reps) reps in \(.applicationName)"
            ]
        )
    }
}
```

**Comment by wrbl606** [comment]
For non-entity based parameters the "confirmation" step is necessary, [see Apple's stand on that issue](https://forums.developer.apple.com/forums/thread/759909?answerId=798842022#798842022). For your specific use-case, I think the "reps" parameter can be made into an entity, fed to the OS with example instances in a range e.g. 1-100.

**Comment by caleb654** [comment]
Ah ok thank you for that info. I really appreciate your help! I'll go ahead and close this issue.
