### ISSUE TITLE
AppIntents is not working when the APP is closed.

### ISSUE THREAD

**Issue by JErazo7** [monterail/intelligence#4]
Hello, maybe there is a way to make it work when the app is closed (terminated state). It is just working when the app is in the background.

I attach a video to see the behavior: 

https://github.com/user-attachments/assets/0c0940fe-6269-459a-8051-d23f17705875

**Comment by PhilipHayes** [comment]
What did you do to solve this? 
I ended up creating a background isolate that ran but I needed to set up a way to kill the isolate on demand to avoid being flagged by the system.
